import { StrictMode, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';
import Header from './components/Header.jsx';
import Body from './components/Body.jsx';
import Results from './components/Results.jsx';
import FeedbackWidget from './components/FeedbackWidget.jsx';
import { handleFeedback } from './utils/bodyUtils.js';

const DEV = import.meta.env.DEV;
// const WP_PREFIX = DEV ? '/api' : '';               // proxy in dev, none in prod
// const WP_BASE   = `${WP_PREFIX}/wp-json/canopydb`; // adjust if your namespace differs

const API_ORIGIN = DEV ? '' : 'https://engexpstaging.wpengine.com';
const WP_BASE = `${API_ORIGIN}/wp-json/canopydb`;

// qs helper
const qs = (obj = {}) => {
  const s = new URLSearchParams(obj);
  return s.toString() ? `?${s.toString()}` : '';
};

// Generic GET → JSON with strong errors
async function apiGet(path, params) {
  // path must start with '/' e.g. '/hangerarmname/'
  const url = `${WP_BASE}${path}${qs(params)}`;
  const res = await fetch(url, { headers: { accept: 'application/json' } });
  if (!res.ok) {
    const ct = res.headers.get('content-type') || '';
    const body = ct.includes('application/json')
      ? await res.json().catch(() => ({}))
      : await res.text();
    const bodyPreview = typeof body === 'string' ? body.slice(0, 300) : JSON.stringify(body).slice(0, 300);
    throw new Error(`Unexpected response (${res.status}) from ${url}\nCT: ${ct}\n${bodyPreview}`);
  }
  return res.json();
}

function MainApp() {
  const [form, setForm] = useState({
    system: "Wall-Mounted Canopy", wind_speed: "", ground_snow_load: "", type: "Suspended Canopy", exposure_category: "", host_material: "", roofing_style: "Deck Pan", roof_element_item_name: "", installation_use: "Commercial",
    roof_element_direction: "", canopy_total_x_width_projection: "", canopy_total_y_length: "", spacing_between_hanger_arms_or_struts: "", corner_canopy_condition: "", if_no_diagonal_strut_which_front_gutterbeam_supp_decking: "Neither (Decking Meets At The Corner)",
    diagonal_strut_condition: "", hanger_arm_height_above_canopy: "", hanger_arm_attachment_distance_from_canopy_edge: "", canopy_installation_height: "", mean_roof_height: "", upper_roof_length: "",
    deck_pan_overhang: "0", numof_screws_for_roof_element_to_beam: "", rafter_spacing: "24", beam_type: "Gutter Beam", beam_item_name: "", perimeterBeamOverhangValue: "0", strut_beam_item_name: "",
    hanger_arm_item_name: "", client_top_wall_plate_options: "", top_wall_plate_anchor_type_dc_or_tb: "", top_wall_plate_anchor_dia_selection: "", bottom_anchor_connection_dc_or_tb: "", bottom_anchor_connection: "", bottom_anchor_dia_selection: "",
  });
  const [calc, setCalc] = useState(null);
  const [loading, setLoading] = useState(false);

  return (
    <StrictMode>
      <Header />
      <FeedbackWidget onSubmit={handleFeedback} />
      {/* pass api + WP_PREFIX if Body needs to build its own URLs */}
      <Body form={form} setForm={setForm} onCalc={setCalc} onLoadingChange={setLoading} />
      {loading && (
        <div className="max-w-4xl mx-auto px-4 py-6 text-center text-gray-700">Calculating…</div>
      )}
      {!loading && calc && <Results form={form} calc={calc} />}
      {!loading && !calc && (
        <div className="max-w-4xl mx-auto px-4 py-6 text-center text-gray-500">
          Fill the form and click <span className="font-semibold">Calculate</span> to see results.
          This calculator is currently in beta testing with full functionality. While the underlying calculations have been tested, occasional glitches may occur, particularly if input data is ambiguous or incomplete. All information and results displayed are for illustrative purposes only and should not be relied upon for design, permitting, or construction. Users are solely responsible for the accuracy and validity of the data they enter into this tool. No result generated by this tool constitutes formal, official, or binding engineering advice. Use of this tool does not create a professional services relationship. A certified design and approval by a licensed Professional Engineer of the firm is required before any action is taken. Engineering Express disclaims all liability for errors, omissions, delays, losses, injuries, or damages arising from use of this tool or the information provided.        </div>
      )}
    </StrictMode>
  );
}

const isDev = DEV;

if (!isDev) {
  const origFetch = window.fetch;
  window.fetch = (input, init) => {
    const url = typeof input === 'string' ? input : (input?.url || '');
    if (url.startsWith('/api/')) {
      const fixed = 'https://engexpstaging.wpengine.com' + url.replace(/^\/api/, '');
      return typeof input === 'string' ? origFetch(fixed, init) : origFetch(new Request(fixed, input), init);
    }
    return origFetch(input, init);
  };
}



if (isDev) {
  const root = document.getElementById('root');
  if (root) createRoot(root).render(<MainApp />);
} else {
  const boot = () => {
    const host = document.getElementById('canopy-calculator-host');
    const hostEmailAttr = host?.getAttribute('data-wp-email');
    if (!host || host.shadowRoot) return;

    const shadowRoot = host.attachShadow({ mode: 'open' });
    const mountNode = document.createElement('div');
    shadowRoot.appendChild(mountNode);

    // CSS sits next to the JS file in /assets/, so use same-dir URL
    const cssUrl = new URL('./canopy-calculator-ems.css', import.meta.url).href;

    // minimal base reset so UI is visible even if CSS fails
    const baseStyle = document.createElement('style');
    baseStyle.textContent = `*,*::before,*::after{box-sizing:border-box;border-style:solid}`;
    shadowRoot.appendChild(baseStyle);

    fetch(cssUrl)
      .then(r => {
        if (!r.ok) throw new Error(`CSS ${r.status} ${r.statusText}`);
        return r.text();
      })
      .then(css => {
        const style = document.createElement('style');
        style.textContent = css;
        shadowRoot.appendChild(style);
        createRoot(mountNode).render(<MainApp />);
      })
      .catch(err => {
        console.error('[EMS React calc] CSS load failed:', err);
        createRoot(mountNode).render(<MainApp />); // still render without Tailwind
      });
  };

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', boot, { once: true });
  } else {
    boot();
  }
}
